apiVersion: batch/v1
kind: CronJob
metadata:
  name: nodejs-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: nodejs-cronjob
          labels:
            name: nodejs-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: nodejs-cronjob
              image: ghcr.io/ahmadirfaan/node-js-job:1.0
              imagePullPolicy: Always
          imagePullSecrets:
            - name: dockerconfigjson-github-com