apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-nginx
  labels:
    name: daemon-nginx
spec:
  selector:
    matchLabels:
      name: daemon-nginx
  template:
    metadata:
      name: daemon-nginx
      labels:
        name: daemon-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1


#  Saat menggunakan Replica Set atau Replication Controller,
#  Pod akan dijalankan di Node secara random oleh si Kubernetes
#  Jika kita ingin menjalankan Pod di setiap Node yang ada di Kubernetes,
#  dan tiap Pod hanya boleh jalan 1 di Node, kita bisa menggunakan Daemon Set
#  Secara default Daemon Set akan menjalankan Pod di setiap Node yang ada di Kubernetes Cluster,
#  kecuali jika kita meminta hanya jalan di Node tertentu
#  contoh kasus penggunaan daemonsets, Aplikasi untuk monitoring Node, Aplikasi untuk mengambil log di Node
#  Dan sejenisnya
