# label berguna untuk melakukan query selector/untuk mencari 
# resources sesuai dengan label yang telah ditentukan
# dapat menambahkan labels sebanyak-banyaknya
# cara command untuk pod "kubectl create -f namafile.yaml"
# command dengan semua labelsnya "kubectl get pods --show-labels"
# cara cari pod dengan label yang sesuai "kubectl get pod -l version=1.4.5"

apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-label #nama pod harus unik
  labels:
    teams: finance
    version: 1.4.5
    environment: production
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80 